#!/bin/bash

sudo apt-get update
sudo apt-get install -y git

curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo usermod -aG docker your-user

cd /tmp
git clone https://github.com/ttousai/mpdvops.git
cd mpdvops/src

bash run.sh
